#goal definition
string root_tf_frame_id
string camera_tf_frame_id
string target_tf_frame_id
---
#result definition
bool succeed
int32 yaw_deg
int32 pitch_deg
int32 yaw_gap_deg
int32 pitch_gap_deg
---
#feedback definition